### ISSUE TITLE
unable to open database file

### ISSUE THREAD

**Issue by jysgit** [jlice/leetcode-publisher#4]
嗨，今天用的时候跑出这个error：
Traceback (most recent call last):
  File "src/app.py", line 456, in <module>
    _main()
  File "src/app.py", line 449, in _main
    rg = RepoGen(conf)
  File "src/app.py", line 45, in __init__
    self.dao = Dao(sqlite3.connect(os.path.join(LP_PREFIX, '_cache', 'leetcode.db')))
sqlite3.OperationalError: unable to open database file
请问还有在维护吗 谢谢

**Comment by straicat** [comment]
早已失效了 暂时没时间维护

**Comment by CallanBi** [comment]
@jlice hi，受到你这个项目的启发，写了个功能类似的客户端 [Leetecho](https://callanbi.top/leetecho/)，借鉴了模板生成的样式。非常感谢贡献了这个项目！

@jysgit 可以试试这个，体验还是很友好的，看看符不符合你的需求
